graphql/graphql-relay-js

src/__tests__/starWarsData.js
src/__tests__/starWarsSchema.js

A back-end implementation with a real database wouldn't have direct access to the full dataset.
See facebook/relay#67

Update Star Wars example schema to mimic real database API

---

src/connection/connection.js

connectionDefinitions function’s response type is GraphQLObjectType, which is wrong.
GraphQLConnectionDefinitionsType would describe response type right.

GraphQLConnectionDefinitions type

---

src/node/node.js

I was recently building a toy project with Relay and GraphQL where I
needed to encode extra information in my global ID. To do this, I
decided to add an `idFetcher` argument to my `globalIdField` call that
returned a string that was delimited by a `:`. However, this did not
work because of how globalIds are deconstructed in `fromGlobalId`, so
instead of getting my encoded ID (e.g. `123:test`) I just got the ID
part (e.g. `123`).
To prevent this confusion, it might be nice to either warn when this
happens or use a different strategy in `fromGlobalId` than `split`. In
this commit, I swap out the `split` for a performant
`indexOf`/`substring` approach that satisfies this use-case. Of course,
a regex version would also work here:
```js
export function fromGlobalId(globalId: string): …
```

Allow for IDs to contain `:` characters

---

src/connection/arrayconnection.js
src/index.js

We already export a `cursorForObjectInConnection` method which itself calls `offsetToCursor`, but because it relies internally on `Array.prototype.indexOf` to derive the offset, it is not well suited for use cases where objects may be equivalent but not strictly equal (`===`).
By exporting `offsetToCursor`, schema authors can derive cursors on their own without having to go through `cursorForObjectInConnection`. This mirrors what we do with `cursorToOffset`, which is already exported.
Fixes: https://github.com/graphql/graphql-relay-js/issues/29

Expose `offsetToCursor` method

---

README.md

This was fixed in #24, but that one has gone stale and needs updating so
I am clearing it out and pushing this up as the subset of that commit
which still applies and is useful.

Extract typo fix from #24

---

README.md
src/__tests__/starWarsSchema.js
src/node/__tests__/global.js
src/node/node.js

I got tired of always repeating the parent type's name. I'd imagine others would as well.

Infer globalIdField type name if not specified

---

src/index.js

It seems that the `pluralIdentifyingRootField` function, while documented, is never exported from the `graphql-relay-js` package. This PR adds it to the list of exports.

Export `pluralIdentifyingRootField` function

---

src/connection/__tests__/arrayconnection.js

Pretty self explanatory, testing for `last: 3` is the same as the `exactly right` test underneath it.

Testing for too many should test last: 4, not last: 3

---

src/node/node.js

Passing ResolveInfo to globalIdField idFetcher give the opportunity to build an id using the `rootValue`.
I think this can be very useful when you are working with multi-language application and need a simple and localized way to ensure Relay.Store consistent update.

Passing ResolveInfo to globalIdField idFetcher

---

src/node/__tests__/plural.js
src/node/plural.js

Updated `pluralIdentifyingRootField` to pass the resolve info object through to the provided `resolveSingleInput`, so that `rootValue` fields (access tokens, etc.) can be utilized while resolving values. The unit test is also updated to exercise resolve info pass-through.

Pass resolve info to pluralIdentifyingRootField's resolveSingleInput

---

src/connection/connection.js

This appears to be a copy/paste error. 
Not sure what the correct description would be beyond that it is a list of edge typed items.

Fix connection edges field description

---

package.json
src/__tests__/starWarsMutationTests.js
src/node/__tests__/global.js
src/node/__tests__/node.js
src/node/__tests__/nodeasync.js
src/node/__tests__/plural.js
src/node/node.js
src/node/plural.js

The third argument to the `resolve` functions is now a `context`, and what was formerly the third argument (the info containing `rootValue` and so on) is now the fourth argument.
See:
https://github.com/graphql/graphql-js/releases/tag/v0.5.0
Also squashes in additional test fixes (additional `types` declarations) from @taion:
https://github.com/graphql/graphql-relay-js/commit/73c5c3fefb9f7ec5ee963f54efab73ae1068fb20
These are required as noted in the v0.5.0 release notes.
> Types can now be explicitly provided to new `GraphQLSchema({ types: [...] })`. Types which implement an interface but are otherwise not referenced as a field return type are no longer automatically added to the Schema!

Make compatible with graphql-js v0.5.0

---

src/mutation/__tests__/mutation.js
src/mutation/mutation.js

This is a fix for graphql@0.5.0 which changed the params passed to resolve.

added context param to mutation resolve

---

.eslintrc
package.json

`master` is currently failing lint with no changes:
```
src/connection/arrayconnection.js
33:15  error  'T' is not defined  no-undef
35:15  error  'T' is not defined  no-undef
51:30  error  'T' is not defined  no-undef
53:23  error  'T' is not defined  no-undef
67:21  error  'T' is not defined  no-undef
70:15  error  'T' is not defined  no-undef
133:30  error  'T' is not defined  no-undef
136:23  error  'T' is not defined  no-undef
162:15  error  'T' is not defined  no-undef
163:11  error  'T' is not defined  no-undef
```
This PR adds `eslint-plugin-flowtype` which is designed to fix this issue and other stylistic rules.

Fix no-undef lint error in Flow definitions

---

src/utils/__tests__/base64.js
src/utils/base64.js

This PR just changes the coding scheme used for `base64()` and `unbase64()`, so that non-ASCII characters can be used in IDs. This is relevant for example for translation applications ([guigrpa/mady](https://github.com/guigrpa/mady)).
I have also added some tests on `utils.js`.
Related issues: #62, facebook/relay#755.

Use UTF-8 instead of ASCII for base64 conversion

---

src/__tests__/starWarsSchema.js
src/mutation/__tests__/mutation.js
src/mutation/mutation.js

I would like to define a relay compatible graphql server without imposing needless restrictions on the schema like requiring clients to send a clientMutationId in requests and ask for a clientMutationId field in the mutation payload.
graphql-relay-js defines these fields as non-null, but [Relay Input Object Mutations Specification](https://facebook.github.io/relay/graphql/mutations.htm) only says that they *may* be non-null.
I would also like to remove the need to even have the clientMutationId as part of the relay spec entirely, since there is no reason why the client should need to send it over the network, as shown in https://github.com/facebook/relay/pull/1083.  However, making that transition on the relay client would require the server to first make the clientMutationId field …

Remove non-null restriction on clientMutationId field definitions.

---

README.md

#37 exposed the `offsetToCursor` method to fix what seems to be a pretty common use-case.
It took some digging to find #29 which had the information I needed. I thought it would be helpful to have it documented in the README.

added `offsetToCursor` to documentation

---

package.json
scripts/mocha-bootload.js

`graphql-js` 0.7.0 was released on 8/25, but there is currently no compatible version of `graphql-relay-js` due to `peerDependencies`. The tests pass fine with 0.7.0, but this will likely fail CI anyway until #100 is merged.

Update graphql in devDependencies, use exact versions

---

package.json
src/mutation/__tests__/mutation.js
src/mutation/mutation.js

Adds an optional description field to the mutationWithClientMutationId function.

Add description field to mutationWithClientMutationId

---

src/node/__tests__/node.js
src/node/node.js

Based upon @josephsavona's comments, a top-level `nodes` field is an established pattern:
"This is similar to the above, except that the user selects multiple items such that there are a list of ids to fetch on the detail view. The canonical approach is to use a nodes(ids: [id1, id2, ...idn]) query for the detail view to fetch all the information for all of the items in a single query.
The nodes field should accept a single argument ids: [ID!]!. It should return one result per input id, in an order matching the input arguments. For ids that do not exist or cannot be fetched, it should return null in order to ensure the ordering requirement." - https://github.com/facebook/relay/issues/1496
Wasn't sure to what extent I should duplicate existing node field expectations. Also wasn't sure …

Add nodes field to nodeDefinition

---

src/mutation/__tests__/mutation.js
src/mutation/mutation.js

So, we can avoid something like:
```js
const mutationType = new GraphQLObjectType({
name: 'Mutation',
fields: {
simpleMutationWithDeprecationReason: {
...simpleMutationWithDeprecationReason,
deprecationReason: 'Just because',
},
},
});
```

allow deprecationReason in mutationWithClientMutationId

---

README.md

I was confused why `offsetToCursor` and `cursorToOffset` were indented in the readme, I think it's a mistake because it's a flat [export](https://github.com/graphql/graphql-relay-js/blob/72af3f16aae923ef07efc4f768ea0d26a1c93a55/src/index.js#L19-L28) of all the helpers in the list.

fix sub point indentation of the last two connection helpers in the readme

---

package.json
yarn.lock

As Flow 0.38 is pretty old now and the GraphQL typedefs have changed, i'd like to suggest to update them to the most recent versions. GraphQL and Flow have been updated in the same PR because Flow 0.56 causes errors with GraphQL 0.9.1.

Update flow to 0.57

---

src/index.js

This simply re-exports the connection flow types for creating connection types in the schema.

Fix #173 - Export flow types

---

src/node/node.js

The current typing erases the context type parameter on the node definitions, leading to incorrect incompatibility errors when using nodeField or nodeFields on a type where the other fields have a type parameter for the context.
cc @yodaiken

Parametrize GraphQLNodeDefinitions on TContext

---

package.json

This is actually breaking my test CI and probably not only mine.
I am not really sure how it ended up there since @kassens' [PR](https://github.com/graphql/graphql-relay-js/pull/222) was adding correctly.
Hope I haven't missed anything important but the test are passing 😄 
would you consider patching the npm version ?

chore(dependencies): use prettier as a dev dependency

---

src/connection/arrayconnection.js

Hi good people 👋 
I would like to suggest to use more strict type for connection data - `$ReadOnlyArray<T>`
**Why?**
We define all our types for data on GraphQL server as read-only, so passing data to `connectionFromArray` fails on flow unless we change the type to normal array or do workaround like `[...children]`:
```
connectionFromArray<Item>(children, args);
// Cannot call `connectionFromArray` with `children` bound to `data` because read-only array type [1] is incompatible with array type [2]
```
With these changes, it should be possible to opt-in for `$ReadOnlyArray<T>` while `Array<T>` would still work as well.

Use $ReadOnlyArray type for connection data

---

src/node/__tests__/plural.js
src/node/plural.js

Remove unnecessary async code, part 2

---

.babelrc.json
.eslintignore
.eslintrc.yml
.gitignore
.prettierignore
package.json
resources/build.js
resources/utils.js

This aligns the build process with the one currently used by `express-graphql`

Add build script

---

package.json
src/connection/arrayconnection.d.ts
src/connection/connection.d.ts
src/connection/connectiontypes.d.ts
src/index.d.ts
src/mutation/mutation.d.ts
src/node/node.d.ts
src/node/plural.d.ts

The DefinitelyTyped definitions are pretty misaligned with the Flow definitions. A good example is `ConnectionConfig.nodeType` which is typed as GraphQLObjectType in Flow (here) but is effectively typed as GraphQLOutputType in DT ([here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/graphql-relay/index.d.ts#L70)). I'll do a separate PR to sync these with Flow so that there's a clear record of what changed. The only thing I did sync was the comments to reduce the diff for the next PR.

Add TypeScript declaration files

---

src/connection/arrayconnection.d.ts
src/connection/arrayconnection.js
src/connection/connection.d.ts
src/connection/connection.js
src/connection/connectiontypes.d.ts
src/connection/connectiontypes.js
src/node/node.d.ts
src/node/node.js
src/node/plural.js

All credits goes to @danielrearden
Closes #276

Remove maybe types

---

src/__testUtils__/__tests__/dedent-test.js
src/__testUtils__/dedent.js
src/mutation/__tests__/mutation-test.js
src/node/__tests__/node-test.js
src/node/__tests__/plural-test.js

Reuse `dedent` from `graphql-js`

tests: replaces introspection queries with printing schemas

---

src/connection/__tests__/connection-test.js
src/connection/connection.js

All credits goes to @excitement-engineer
Closes #178

Added a description to the pagination arguments.

---

src/mutation/__tests__/mutation-test.js
src/mutation/mutation.d.ts
src/mutation/mutation.js

mutationWithClientMutationId: pass through `extensions`

---

src/node/node.d.ts
src/node/node.js

nodeDefinitions: Allow to pass number as ID values

---

.eslintrc.yml
src/utils/__tests__/base64-test.js
src/utils/base64.js

Previously we used Node's API for converting to/from base64
but it limits portability of this library to defirent enviroments
include Deno
Fixes #152

Switch to custom base64 implementation

---

src/mutation/__tests__/mutation-test.js
src/mutation/mutation.js

Allow mutations to return custom classes

---

.eslintrc.yml
.flowconfig
src/__tests__/starWarsData.js
src/connection/arrayConnection.js
src/connection/connection.js
src/mutation/mutation.js
src/node/node.js
src/node/plural.js

In preparation for TS migration

Flow: switched to exact object by default

---

src/connection/arrayConnection.d.ts
src/connection/connection.d.ts
src/mutation/mutation.d.ts
src/node/node.d.ts
src/node/plural.d.ts

This is a breaking change. There isn't any history on the files we we export these if users have any issues we can revert this change. 
From #340 36c8ad7a5c1c7c83a1d57d4dfb82ba211d697147

feat: remove typescript only interface export

---

src/connection/connection.js

TypeScript Migration #340 we are cleaning up these types 49746d6b4928acb01967b72020770cdaae521267 so getting this change here.

feat: use object freeze for connection args

---

package-lock.json
package.json

fix: lock only major version

---

src/__tests__/starWarsSchema.js
src/node/__tests__/global-test.js
src/node/__tests__/node-test.js
src/node/__tests__/nodeAsync-test.js

Extracted from TS conversion #340

Add explicit typing of recursive variables

---

package-lock.json
package.json
src/__tests__/starWarsSchema.ts
src/connection/__tests__/connection-test.ts
src/connection/connection.ts
src/mutation/__tests__/mutation-test.ts
src/mutation/mutation.ts
src/node/__tests__/global-test.ts
src/node/__tests__/node-test.ts
src/node/__tests__/nodeAsync-test.ts
src/node/__tests__/plural-test.ts

Switch to graphql@16.2

---

src/connection/__tests__/arrayConnection-test.ts
src/utils/base64.ts

Fixes #358
Note: it's temprorary workaround until we design a better API

Fix: 'fromGlobalId' trowing on invalide UTF code points
